spring:
  datasource:
    url: jdbc:h2:/project1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect:
    show-sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
